services:
  frontend:
    build: .
    container_name: fernangus-films
    volumes:
      - ./app:/var/www/html/app
      - ./config/prod/virtualhost/fernangus-films.chickenkiller.com.conf:/etc/apache2/sites-enabled/fernangus-films.chickenkiller.com.conf
      - ./config/prod/virtualhost/urls.js:/var/www/html/app/public_html/config/urls.js
    ports:
      - "80:80"
    restart: always  # Se inicia automáticamente en producción
